# version: '3.8'   # opcional, se puede omitir en versiones nuevas

services:
  postgres-service:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: sonarqube
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sonar-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sonar"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 20s

  sonarqube-service:
    image: sonarqube:community
    container_name: sonarqube-container
    depends_on:
      postgres-service:
        condition: service_healthy
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres-service:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: 1234
    ports:
      - "9000:9000"
    volumes:
      - sonarqube-data:/opt/sonarqube/data
      - sonarqube-extensions:/opt/sonarqube/extensions
      - sonarqube-logs:/opt/sonarqube/logs
    networks:
      - sonar-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: always

volumes:
  postgres-data:
  sonarqube-data:
  sonarqube-extensions:
  sonarqube-logs:

networks:
  sonar-net:
    driver: bridge
